version: 2.1

# ------------------------------------------------------------------------------
# shared configuration
# ------------------------------------------------------------------------------

attach_workspace: &attach_workspace
  attach_workspace:
    at: '.'

persist_workspace: &persist_workspace
  persist_to_workspace:
    root: '.'
    paths: [ '.' ]

defaults: &defaults
  working_directory: '~/project'
  docker: [ {image: 'mcr.microsoft.com/powershell:7.0.0-preview.4-alpine-3.8'} ]

# ------------------------------------------------------------------------------
# pipeline
# ------------------------------------------------------------------------------

workflows:

  version: 2

  pipeline:
    jobs:
      - configure_powershell
      # - tf_validate:
      #     requires: [ fetch_code ]
      - tf_fmt:
          requires: [ fetch_code ]
      # - tf_lint:
      #     requires: [ fetch_code ]

# ------------------------------------------------------------------------------
# jobs
# ------------------------------------------------------------------------------

jobs:

  configure_powershell:
    <<: *defaults
    steps:
      - checkout
      - run:
          name: 'Install Powershell Modules'
          command: |
            Install-Module -Name AWSLambdaPSCore -Scope CurrentUser -Force
            Install-Module -Name AWS.Tools.EC2 -Scope CurrentUser -Force
            Import-Module -Name AWSLambdaPSCore
            Import-Module -Name AWS.Tools.EC2

      - *persist_workspace

  terratest_build:
    docker:
      - image: qldockerdtr.rockfin.com/hal/hal-build-environments:iac
    working_directory:  '/root/go/src/git.rockfin.com/aws-vpc-tf/'
    steps:
      - *attach_workspace
      - checkout
      - run:
          name: "setup env"
          command: |
                mv /usr/bin/terraform-0.12 /usr/bin/terraform
                echo 'export PATH=$PATH:/usr/local/go/bin' >> $BASH_ENV
                echo 'export GOPATH=/root/go' >> $BASH_ENV
      - run:
          name: "install go"
          command: |
                curl -sSL -o "go.tar.gz" "https://dl.google.com/go/go1.12.5.linux-amd64.tar.gz"
                tar -C /usr/local -xzf go.tar.gz
      - run:
          name: "grab dep binary"
          command: |
                curl -L -s https://github.com/golang/dep/releases/download/v0.5.4/dep-linux-amd64 -o /usr/local/go/bin/dep
                chmod +x /usr/local/go/bin/dep
      - run:
          name: "Grab go imports"
          command: "dep init && dep ensure -vendor-only"
      - run:
          name: 'Run All Terratest tests'
          command: 'go test --timeout 60m ./... -v' # add -v for all logs
