name: CI

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: windows-latest

    steps:
    - uses: actions/checkout@v2
    - name: Run a one-line script
      run: echo Hello, world!
    - name: Install Dependencies
      run: |
        Install-Module -Name AWS.Tools.CognitoIdentityProvider
        Install-Module -Name AWS.Tools.SimpleSystemsManagement
    - name: Run a multi-line script
      run: |
        Write-Host "Hello World!"
