name: Build and Package Powershell Lambda
env:
    OUTPUT_PATH: ${{ github.workspace }}/.output

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout Code 
      uses: actions/checkout@v2
      with:
        path: main
    - name: Update PIP
      run: pip install --upgrade pip
    - name: Install Powershell Modules
      run: |
        pwsh -command Write-Host 'Hello Wrold'
        pwsh -command Install-Module -Name AWSLambdaPSCore -Scope CurrentUser -Force
        pwsh -command Import-Module -Name AWSLambdaPSCore
    - name: Package Up Artifact for Lambda
      run: |
        mkdir artifact
        pwd
        ls -la ${{ github.workspace }}/main
        cd ~
        ls -la
