name: Build and Package Powershell Lambda
env:
    OUTPUT_PATH: ${{ github.workspace }}/.output
    S3_BUCKET_NAME: testinglambdaautionforstuff
    LAMBDA_FUNCTION: testlambda

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:
    runs-on: [ubuntu-latest]
    steps:
    - name: Checkout Code
      uses: actions/checkout@v2
      with:
        path: main
    - name: Update PIP
      if: success()
      run: pip install --upgrade pip
    - name: Install Powershell Modules
      if: success()
      run: |
        pwsh -command Write-Host 'Install and Import AWS Powershell Lambda Core'
        pwsh -command Install-Module -Name AWSLambdaPSCore -Scope CurrentUser -Force
        pwsh -command Import-Module -Name AWSLambdaPSCore
    - name: Package Up Artifact for Lambda
      if: success()
      run: |
        ls -la ${{ github.workspace }}/main
        pwsh -command New-AWSPowershellLambdaPackage -ScriptPath ${{ github.workspace }}/main/new-org-account.ps1 -OutputPackage ${{ env.OUTPUT_PATH }}/new-org-account.zip
    - name: Upload Artifact
      if: success()
      uses: actions/upload-artifact@v1
      with:
        name: new-org-account
        path: ${{ env.OUTPUT_PATH }}/new-org-account.zip
  deployment:
      runs-on: [ubuntu-latest]
      needs: [build]
      steps:
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v1
        with:
            aws-access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
            aws-secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
            aws-region: us-east-2
      - name: Test AWS Credentials
        if: success()
        run: aws s3 ls 
      - name: Download Build Artifact
        uses: actions/download-artifact@v1
        with:
            name: new-org-account
            path: ${{ env.OUTPUT_PATH }}
      - name: S3 Upload Artifact
        run: aws s3 cp ${{ env.OUTPUT_PATH }}/new-org-account.zip s3://${{ env.S3_BUCKET_NAME }}/new-org-account-${{ github.sha }}.zip
      - name: Update Lambda Code
        if: success()
        run: |
          aws lambda update-function-code \ 
          --publish \
          --function-name  ${{ env.LAMBDA_FUNCTION }} \
          --s3-bucket ${{ env.S3_BUCKET_NAME }} \
          --s3-key new-org-account-${{ github.sha }}.zip
        
        
       

