name: CI

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Update PIP
      run: pip install --upgrade pip
    - name: Install Powershell
      run: |
        sudo apt-get install -y powershell
        pwsh -command Write-Host 'Hello Wrold'
