name: CI

on: 
  push:
    branches:
      - master
  pull_request:
    branches:
      - master

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - name: Install Updates
      run: |
        apt update && apt upgrade -y
    - name: Install Powershell
      run: apt-get install -y powershell
